version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: wahyubucil
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: community
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
